# Generated by Django 5.2.4 on 2025-07-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='poster/')),
                ('release_year', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('DR', '드라마'), ('CM', '코미디'), ('AC', '액션'), ('RM', '로맨스'), ('TH', '스릴러'), ('HR', '공포'), ('SF', 'SF'), ('AN', '애니메이션'), ('DC', '다큐멘터리'), ('ET', '기타')], max_length=2)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('running_time', models.PositiveIntegerField(help_text='단위: 분')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
